# Generated by Django 5.2.4 on 2025-08-02 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0009_upcomingevent_teacher_grade_actionrequired"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customuser",
                to="college.grade",
            ),
        ),
    ]
