# Generated by Django 5.2.4 on 2025-08-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0003_alter_principal_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="principal",
            name="user",
        ),
    ]
