# Generated by Django 5.2.4 on 2025-08-02 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0005_daily_login_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daily_login",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="raiseleave",
            name="approval_by",
        ),
        migrations.RemoveField(
            model_name="raiseleave",
            name="leave_raiser_content_type",
        ),
        migrations.RemoveField(
            model_name="raiseleave",
            name="leave_raiser_object_id",
        ),
        migrations.AddField(
            model_name="raiseleave",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
