# Generated by Django 5.2.4 on 2025-08-02 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0006_remove_daily_login_teacher_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisciplinaryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_date", models.DateField()),
                ("description", models.TextField()),
                ("action_taken", models.TextField()),
                (
                    "severity",
                    models.TextField(
                        choices=[
                            ("minor", "minor"),
                            ("major", "major"),
                            ("severe", "severe"),
                        ]
                    ),
                ),
                ("remarks", models.TextField()),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinary",
                        to="college.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tc_number", models.TextField()),
                ("issue_date", models.DateField()),
                ("reason_for_leaving", models.TextField()),
                ("last_class_attended", models.DateField()),
                ("conduct", models.TextField()),
                ("remarks", models.TextField()),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tc",
                        to="college.student",
                    ),
                ),
            ],
        ),
    ]
