# Generated by Django 5.2.4 on 2025-08-02 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0007_disciplinaryrecord_transfercertificate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student_marks",
            name="subject",
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_number", models.TextField()),
                ("exam_type", models.TextField()),
                ("exam_date", models.DateField()),
                (
                    "exam_incharge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Exam",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_invisilator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="college.subject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student_marks",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Student_marks",
                to="college.exam",
            ),
        ),
    ]
