# Generated by Django 5.2.4 on 2025-08-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0009_upcomingevent_teacher_grade_actionrequired"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamIncharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("age", models.BigIntegerField()),
                ("gender", models.TextField()),
                ("contact", models.TextField()),
                ("qualification", models.TextField()),
                ("employee", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ExamInvigilator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("age", models.BigIntegerField()),
                ("gender", models.TextField()),
                ("contact", models.TextField()),
                ("qualification", models.TextField()),
                ("employee", models.TextField()),
            ],
        ),
    ]
