# Generated by Django 5.2.4 on 2025-08-04 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0010_examincharge_examinvigilator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="exam_invisilator",
        ),
        migrations.AddField(
            model_name="exam",
            name="exam_invigilator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="college.examinvigilator",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_incharge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Exam",
                to="college.examincharge",
            ),
        ),
    ]
