# Generated by Django 5.2.4 on 2025-08-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0011_remove_exam_exam_invisilator_exam_exam_invigilator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="raiseleave",
            name="instance_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
