# Generated by Django 5.2.4 on 2025-08-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0012_raiseleave_instance_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily_login",
            name="logout_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
