# Generated by Django 5.2.4 on 2025-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0013_alter_daily_login_logout_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college_name", models.TextField()),
                ("address", models.TextField()),
                ("phone", models.BigIntegerField()),
            ],
        ),
    ]
