# Generated by Django 5.2.4 on 2025-08-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0014_college"),
    ]

    operations = [
        migrations.AddField(
            model_name="feestructure",
            name="instance_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
