# Generated by Django 5.2.4 on 2025-08-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0015_feestructure_instance_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fee_details",
            name="course",
        ),
        migrations.RemoveField(
            model_name="student",
            name="course",
        ),
    ]
