# Generated by Django 5.2.4 on 2025-08-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0016_remove_fee_details_course_remove_student_course"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Feestructure",
        ),
    ]
