# Generated by Django 5.2.4 on 2025-08-08 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college", "0018_course_feestructure_feeterm_feecomponent"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Student",
                to="college.course",
            ),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="admission_type",
            field=models.CharField(
                choices=[
                    ("Regular", "Regular"),
                    ("Lateral_Entry", "Lateral_Entry"),
                    ("Management_Quota", "Management_Quota"),
                ],
                max_length=20,
            ),
        ),
    ]
